# This yaml defines the allowed values for entries in the config
# Entries here are mapped to/used as function (or used as regex) to check the value in the actual config
# - functions for a single entry are separated by single underscore '_'
# - functions applied to each entry of a list are separated by double underscores '__'
# - functions that are basic objects types (int, float, str, bool, list) check match with that [float also allows int]
# - functions with number added: le/ge check size of numeric values, len checks length of list
# - filterset, filtersetdefault, sections, sectionsall & insamplehseet are special functions
# - everything else is treated as regex (needs to match the *full* value)
static_data:
    bpm_manifest_file: str
    csv_manifest_file: str
    egt_cluster_file: str
    genome_fasta_file: str
    genome_gtf_file: str
    pfb_file: str
    GCmodel_file: str
    array_density: str
    array_gaps: str
    genomeInfo_file: str

raw_data_folder: str
data_path: str
log_path: str

settings:
  CNV.calling.tools: list__str__(PennCNV|CBS)
  probe-filter-sets:
    __filterset:
        GenTrainScore: float_le1_ge0
        GenCallScore:  float_le1_ge0
        Position.duplicates: str_(keep|remove|highestGC|highestGT)

  chromosomes: list

  default-filter-set: filtersetnodefault

  PennCNV:
    filter-settings: filterset

  CBS:
    filter-settings: filterset
    SDundo: int
    min.width: int
    LRR.loss: float
    LRR.loss.large: float
    LRR.gain: float
    LRR.gain.large: float
    LRR.male.XorY.loss: float
    LRR.male.XorY.gain: float
    LRR.male.XorY.gain.large: float
    LRR.female.X.loss: float
    LRR.female.XX.loss: float
    LRR.female.X.gain: float
    LRR.female.X.gain.large: float

  postprocessing:
    min.snp: int
    min.length: int
    min.snp.density: float #snps per Mb #TODO: might also want __default__ for this?
    density.windows: int_ge0     #window size for probe density calculation (0.5Mb)
    min.gap.size: str_([0-9+]|__mean\+sd__) #minimum distance between 2 probes to be considered a gap. Number or '__mean+sd__'
    merge.distance: int_ge0
    merge.before.filter: bool
    tool.overlap.greatest.call.min.perc: float_le100
    tool.overlap.median.cov.perc: float_le100
    ## Reference comparison
    min.reciprocal.coverage.with.ref: float_le100

  gene_overlap:
    exclude_gene_type_regex: list__str
    include_only_these_gene_types: list__str

  make_cnv_vcf:
    filter-settings: filterset
    mode: str_(combined-calls|split-tools)
    include_states: list__str__(LOH|gain|loss)
    name_addition: str

allowed_sections:
     - sample.information
     - QC.summary
     - QC.GenCall
     - QC.PennCNV
     - QC.CBS
     - QC.settings
     - reportable.table
     - reportable.plots
     - nonreportable.table
     - nonreportable.plots
     - regions.of.interest
     - virtual.karyotype
     - circo.plot
     - SNP.dendrogram
reports:
  __report:
    file_type: str_(html|pdf)
    include_sections: sectionsall
    exclude_sections: list__sections

    sample.info.extra.cols: list__insamplesheet

    call.data.and.plots:
      filter-settings: filterset
      include.plot: bool
      include.call.table: bool
      include.gene.table.details: str_(All|Call|None)
      plot.flanking.region.relative: float_ge0
      plot.region.minsize.reportable: int_ge10000
      plot.region.minsize.nonreportable: int_ge10000

    thresholds:
      reportable.loh: int
      reportable.cnv: int
      fail.loh: int
      fail.cnv: int
    QCwarnings:
      callrate: list_len2__float__le1
      total_CNV: list_len2__int
      total_LOH: list_len2__int
      loss_gain_ratio: list_len2__int
      sizable_CNV: list_len2__int
      sizable_LOH: list_len2__int
      SNP_distance_reference: list_len2__int
      # overlapping_genes: []
    SNP_comparison:
      filter-settings: filterset
      ignore_filter: bool
      extra_samples: list__insamplesheet
      dendrogram.color.by: str_insamplesheet
      dendrogram.shape.by: str_insamplesheet

wildcard_constraints:
  sample_id: str
  sentrix_pos: str
  sentrix_name: str

tools:
  __tool:
    threads: int
    memory: '[0-9]+M?'
    runtime: str
    cmd-line-params: str
    partition: str