name: cnv-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## General ##
  - python >= 3.9 #sensible default
  - snakemake 
  - r-base >=4.1 #sensible default; maybe pin this?
  - r-tidyverse
  - r-optparse #replace?!
  - r-argparse
  - r-knitr
  - r-rmarkdown
  - r-yaml
  - r-sessioninfo
  - r-devtools
  - r-vcfr
  ## Algorithms ##
  # gtc2vcf
  - gtc2vcf = 1.16 # new/untested
  # CBS
  - bioconductor-dnacopy = 1.68.0
  ## Postprocessing ##
  - bioconductor-plyranges = 1.14.0
  ## R-GADA dependency
  - bioconductor-gviz
  #-bioconductor-genomicranges
  ## Report ##
  - r-ggpubr
  - r-dendextend
  - r-rideogram
  - r-rcolorbrewer
  - r-DT
  #- r-plotly
  - r-patchwork
  - r-circlize # new/untested
  #- r-biocircos # requires r4.2? new/untested
  - r-rcircos # new/untested
