name: cnv-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## General ##
  - python >= 3.9 #sensible default
  - snakemake
  - r-base >=4.1 #sensible default; maybe pin this?
  - r-tidyverse
  - r-argparse
  - r-knitr
  - r-rmarkdown
  - r-yaml
  - r-sessioninfo
  - r-devtools
  - r-vcfr
  ## Algorithms ##
  # Needed to build PennCNV
  - perl = 5.32 #seems to be only version under which PennCNV build properly
  - gcc # in case not available, i.e. on some WSL distros
  # gtc2vcf
  - bcftools-gtc2vcf-plugin = 1.16
  # CBS
  - bioconductor-dnacopy = 1.68.0
  ## Postprocessing ##
  - bioconductor-plyranges = 1.14.0
  ## R-GADA dependency
  - bioconductor-gviz
  #-bioconductor-genomicranges
  ## Report ##
  - r-ggpubr
  - r-dendextend
  - r-rideogram
  - r-rcolorbrewer
  - r-DT
  #- r-plotly
  - r-patchwork
  #- r-circlize # new/untested
  #- r-biocircos # requires r4.2? new/untested
  #- r-rcircos # new/untested
