static_data:
    bpm_manifest_file: static-data/GSAMD-24v3-0-EA_20034606_A2.bpm
    csv_manifest_file: static-data/GSAMD-24v3-0-EA_20034606_A2.csv
    egt_cluster_file: static-data/GSAMD-24v3-0-EA_20034606_A1.egt
    genome_fasta_file: static-data/GRCh38.p13.genome.chr_scaff.fa
    genome_gtf_file: static-data/gencode.v42.basic.annotation.gtf
    pfb_file: static-data/PennCNV-PFB_from_clusterfile-stats.pfb
    GCmodel_file: static-data/PennCNV-GCmodel-GRCh38.gcmodel

raw_data_folder: RAW_DATA
data_path: data_new

settings:
  CNV.calling.tools:
    - PennCNV
    - CBS
    #- GADA
  make_cnv_vcf:
    mode: combined-calls
    name_addition: 'test.'
  report:
    thresholds:
      # Include these sizes in the main tables of the report
      reportable.loh: 2.5e6
      reportable.cnv: 4e5
      # Classify samples as failed from these sizes on
      fail.loh: 5e6
      fail.cnv: 2e6
    # Thresholds for colored table / rec action [orange, red]
    QCwarnings:
      callrate: [0.99, 0.99]
      total_CNV: [10, 50]
      total_LOH: [30, 75]
      loss_gain_ratio: [2, 4]
      sizable_CNV: [5, 10]
      sizable_LOH: [5, 10]
      SNP_distance_reference: [1, 5]
      # # This is hard to set thresholds for, since currentlöy all types of genes are used
      # # -> maybe add a filter for which genes should be used? (may need it's own section in here)
      # overlapping_genes: []
    SNP_comparison:
      include_dendrogram: FALSE
      ignore_filters: FALSE
      #Can add sample_ids here, but not generally recommended to do so, instead use columns from the sample_table
      # enries with __[column] will use all other samples with the same value in [column]
      # entries with _[column] expect a column that contains additional (, separated) sample_ids
      extra_samples: ['__Chip_Name', '__SampleGroup']
      # You can also use additional metadata columns from the sample table
      dendrogram.color.by: 'SampleGroup'
      dendrogram.shape.by: 'Chip_Name'
      

    
tools:
  GenCall:
    threads: 4
    memory: "8000M"
    runtime: "4:00:00"
    cmd-line-params: "--gender-estimate-call-rate-threshold -0.1" #maybe remove?
  gtc2vcf:
    cmd-line-params: "" #"--do-not-check-eof"
    memory: "10000M"
    runtime: "4:00:00"
  knitr:
    memory: "30000M"
    runtime: "30:00"
