static_data:
    bpm_manifest_file: '' #REQUIRED
    csv_manifest_file: '' #Optional (leave empty if not used)
    egt_cluster_file: '' #REQUIRED
    genome_fasta_file: '' #REQUIRED
    genome_gtf_file: '' #REQUIRED
    pfb_file: static-data/PennCNV-PFB_from_clusterfile-stats.pfb  #REQUIRED
    GCmodel_file: static-data/PennCNV-GCmodel-{genome}.gcmodel  #REQUIRED

#TODO group/sort these better?
#sample_table: ''  #Set by wrapper?!
raw_data_folder: ''  #REQUIRED
data_path: data
log_path: logs

settings:
  # Select tools to use and specify order of 'trust' in case of overlapping calls with different states
  # Currently implemented tools (=valid options): PennCNV, GADA, CBS
  CNV.calling.tools:
    - PennCNV
    - GADA
    - CBS
  filter:
    use-filterset: 'full' # basic|highGT|highGC|full [=highGT+GC]
  CBS:
    SDundo: 1
    # LRR threshold for identifying CBS segments as gain/loss 
    LRR.th.value: 0.2
    # adjustment of threshold for X chromosome (female: down, male: up)
    LRR.th.value.Xadj: 0.2
  GADA:
    # Sparsness of bayesian model; higher value gives faster, but fewer results; mostly irrelevant with hig T value
    aAlpha: 0.2
    # Critical parameters of backwards eliminations, sets arbitrary significance level, higher T <> higher significance
    gada.T: 15
    mad.T: 5
    # Minimum required probes in a CNV / LOH call
    MinSegLen: 5
  postprocessing:
    ## Prefiltering is done as follows:
    # [snps] >= min.snp & [length] >= min.lenght & [density, snps/Mb] >= min.snp.density & 
    #  ( [snps] >= min.snp.or.length | [length] > min.length.or.snp )
    ## CNVs of the same state/tool that are <= merge.distance [bp] apart are merged
    # either before or after filtering (based on merge.before.filter)
    min.snp: 5
    min.length: 100
    min.snp.density: 10 #snps per Mb 
    min.snp.or.length: 10
    min.length.or.snp: 2000
    merge.distance: 500
    merge.before.filter: TRUE
    tool.overlap.min.perc: 50
    ## Reference comparison
    min.cnv.coverage.by.ref: 80
  report: 
    thresholds:
      # Include these sizes in the main tables of the report
      reportable.loh: 2.5e6
      reportable.cnv: 4e5
      # Classify samples as failed from these sizes on
      fail.loh: 5e6
      fail.cnv: 2e6
    # Thresholds for colored table / rec action [orange, red]
    QCwarnings:
      callrate: [0.99, 0.99]
      total_CNV: [10, 50]
      total_LOH: [30, 75]
      loss_gain_ratio: [2, 4]
      sizable_CNV: [5, 10]
      sizable_LOH: [5, 10]
      SNP_distance_reference: [1, 5]
      # # This is hard to set thresholds for, since currently all types of genes are used
      # # -> maybe add a filter for which genes should be used? (may need it's own section in here)
      # overlapping_genes: []
    SNP_comparison:
      include_dendrogram: TRUE
      ignore_filters: FALSE
      #Can add sample_ids here, but not generally recommended to do so, instead use columns from the sample_table
      # enries with __[column] will use all other samples with the same value in [column]
      # entries with _[column] expect a column that contains additional (, separated) sample_ids
      extra_samples: ['__Chip_Name']
      # You can also use additional metadata columns from the sample table
      dendrogram.color.by: 'SampleGroup'
      dendrogram.shape.by: 'Chip_Name'


wildcard_constraints:
  chr: "chry|chrx"
  filter: "basic|highGT|highGT|full"
  sentrix_pos: 'R[0-9]{2}C[0-9]{2}'
  sentrix_name: '[0-9]+'
  sample_id: '[a-zA-Z0-9-_]+'

tools:
  GenCall:
    threads: 4
    memory: "8000M"
    runtime: "4:00:00"
    cmd-line-params: "--gender-estimate-call-rate-threshold -0.1" #maybe remove?
  gtc2vcf:
    cmd-line-params: "" #"--do-not-check-eof"
    memory: "10000M"
    runtime: "4:00:00"
  knitr:
    memory: "30000M"
    runtime: "30:00"
  CNV.process:
    memory: "4000M"
    runtime: "30:00"
  PennCNV:
    memory: "4000M"
    runtime: "30:00"
