# This yaml defines the allowed values for entries in the config
# Entries here are mapped to/used as function (or used as regex) to check the value in the actual config
# - functions for a single entry are separated by single underscore '_'
# - functions applied to each entry of a list are separated by double underscores '__'
# - functions that are basic objects types (int, float, str, bool, list) check match with that [float also allows int]
# - functions with number added: le/ge check size of numeric values, len checks length of list
# - filterset, filtersetdefault, sections, sectionsall & insamplehseet are special functions
# - everything else is treated as regex (needs to match the *full* value)
array_definition:
  __array:
    genome_version: str_(hg38|GRCh38|hg19|GRCh37)
    bpm_manifest_file: str    # Path|file
    csv_manifest_file: str    # Path|file
    egt_cluster_file: str     # Path|file
    penncnv_pfb_file: str     # Path|file
    penncnv_GCmodel_file: str # Path|file
    array_density_file: str   # Path|file
    array_gaps_file: str      # Path|file

raw_data_folder: str # Path|dir
data_path: str # Path|dir|no-exist-ok
log_path: str # Path|dir|no-exist-ok

global_settings:
  cache_dir: str # Path|dir|no-exist-ok
  mehari_transcript_db: str # Path|__cache-default__
  hg19_genome_fasta: str # Path|__-use-vep__
  hg38_genome_fasta: str # Path|__-use-vep__
  hg19_gtf_file: str # Path|'__default-gencode__'
  hg38_gtf_file: str # Path|'__default-gencode__'
  hg19_genomeInfo_file: str # Path|'__default-UCSC__'
  hg38_genomeInfo_file: str # Path|'__default-UCSC__'

evaluation_settings:
  CNV_call_categorisation:
    check_score.critical: noneorint
    filters.exclude.critical: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)
    check_score.reportable: noneorint
    filters.exclude.reportable: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)

  summary_stat_warning_levels:   
    last_level_critical: list__str
    call_rate: list_len2__float__le1__ge0
    loss_gain_log2ratio: list_len2__int
    SNP_pairwise_distance_to_reference: list_len2__int
    # SNP_distance_to_reference_span: str
    critical_snvs: list_len2__int
    call_count_excl_filters: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)
    total_calls_CNV: list_len2__int
    total_calls_LOH: list_len2__int
    reportable_calls_CNV: list_len2__int
    reportable_calls_LOH: list_len2__int
    critical_calls_CNV: list_len2__int
    critical_calls_LOH: list_len2__int
    
  collate_output:
    file_format: str_(xlsx|tsv)
    summary_extra_sampletable_cols: list__insamplesheet
    call_table_filters:
      include_call_label: list__str__(Critical|Reportable|Reference genotype)
      exclude_filter_flags: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)
      min_check_score: float_ge0


settings:
  CNV.calling.tools: list__str__(PennCNV|CBS)
  probe-filter-sets:
    __filterset:
        GenTrainScore: float_le1_ge0
        GenCallScore:  float_le1_ge0
        Position.duplicates: str_(keep|remove|highest-GenCall|highest-GenTrain)
        Pseudoautosomal: str_(keep|remove|remove-male)

  default-filter-set: filtersetnodefault

  PennCNV:
    filter-settings: filterset
    enable_LOH_calls: bool
    call.merging:
      merge.gap.absolute: int_ge0
      merge.gap.snps: int_ge0
      call.extension.percent: float_ge0
      maximum.gap.allowed: int_ge0
    filter.minprobes: int_ge0
    filter.minlength: int_ge0
    filter.mindensity.Mb: float_ge0

  CBS:
    filter-settings: filterset
    undo.SD.val: int
    call.merging:
      merge.gap.absolute: int_ge0
      merge.gap.snps: int_ge0
      call.extension.percent: float_ge0
      maximum.gap.allowed: int_ge0
    filter.minprobes: int_ge0
    filter.minlength: int_ge0
    filter.mindensity.Mb: float_ge0
    LRR.loss: float
    LRR.loss.large: float
    LRR.gain: float
    LRR.gain.large: float
    LRR.male.XorY.loss: float
    LRR.male.XorY.gain: float
    LRR.male.XorY.gain.large: float
    LRR.female.X.loss: float
    LRR.female.XX.loss: float
    LRR.female.X.gain: float
    LRR.female.X.gain.large: float

  array_attribute_summary:
    density.windows: int_ge0
    min.gap.size: str_([0-9+]|auto-array)
  
  vcf_output:
    # Which chromosome style to use in the vcf file ("1" vs "chr1")  
    chrom_style: str_(UCSC|keep-original|NCBI|Ensembl)
   
  CNV_processing:
    call_processing:
      filter-settings: filterset
      filter.minprobes: int_ge0
      filter.minlength: int_ge0
      filter.mindensity.Mb: float_ge0
      tool.overlap.greatest.call.min.perc: float_le100_ge0
      tool.overlap.min.cov.sum.perc: float_le100_ge0
      ## Reference comparison
      min.reciprocal.coverage.with.ref: float_le100_ge0
      ## CNV annotations
      gap_area.uniq_probes.rel: list_len2__float
      min.perc.gap_area: float_le1_ge0
      density.quantile.cutoff: float_le1_ge0

    gene_overlap:
      exclude_gene_type_regex: list__str
      include_only_these_gene_types: list__str
      stemcell_hotspot_list: str
      cancer_gene_list: str

    Check_score_values:
      pHaplo_threshold: float_le1_ge0
      pTriplo_threshold: float_le1_ge0
      dosage_sensitive_gene: float_ge0  
      any_roi_hit: float_ge0
      any_other_gene: float_ge0
      large_CN_size_modifier: float_ge1

    Precision:
      size_categories:
        extreme.loh: int
        extreme.cnv: int
        very.large.loh: int
        very.large.cnv: int
        large.loh: int
        large.cnv: int
        medium.loh: int
        medium.cnv: int
      estimate_values:
        multiple_Callers:
          extreme: float_le1_ge0
          very_large: float_le1_ge0
          large: float_le1_ge0
          medium: float_le1_ge0
          small: float_le1_ge0
        PennCNV:
          extreme: float_le1_ge0
          very_large: float_le1_ge0
          large: float_le1_ge0
          medium: float_le1_ge0
          small: float_le1_ge0
        CBS:
          extreme: float_le1_ge0
          very_large: float_le1_ge0
          large: float_le1_ge0
          medium: float_le1_ge0
          small: float_le1_ge0
        Call_has_Gap: float
        HighSNPDensity: float
        
  SNV_analysis:
    filter-settings: filtersetplusnone
    snv_hotspot_table: str # Path|File|exists
    flag_GenCall_minimum: float_ge0_le1
    critical_SNV: list__str__(ROI-match|hotspot-match|hotspot-gene|critical_annotation|any-protein-changing)
    critical_annotations: list__str
    variant_selection:
      Impact: list__str__(HIGH|MODERATE|MODIFIER|LOW)
      Annotation_regex: str
    SNP_clustering_extra_samples: list__insamplesheet


allowed_sections:
  - sample.information
  - QC.summary
  - QC.GenCall
  - QC.PennCNV
  - QC.CBS
  - QC.settings
  - SNV.table
  - SNV.hotspot.coverage
  - SNV.QC.details
  - denovo_calls.table
  - denovo_calls.plots
  - reference_gt_calls.table
  - reference_gt_calls.plots
  - regions.of.interest
  - SNP.dendrogram
  - genome.overview

allowed_plotsections:
  - denovo
  - reference_gt
  - regions_of_interest

reports:
  __report:
    file_type: str_(html|pdf)
    include_sections: sectionsall
    exclude_sections: list__sections
    sample.info.extra.cols: list__insamplesheet

    call.data.and.plots:
      __plotsection:
        exclude_filter: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)
        min_number_plots: int_ge0
        always_include: list__str__(Critical|Reportable)
        include.plot: bool
        include.hotspot.table: bool
        include.gene.table.details: str_(All|Call|None)
        plot.flanking.region.relative: float_ge0
        plot.region.minsize: float_ge10000

    SNV_analysis:
      critical_reasons_with_red_highlight: list__str__(ROI-match|hotspot-match|hotspot-gene|critical_annotation|any-protein-changing)

    SNP_comparison:
      dendrogram.color.by: str_insamplesheet
      dendrogram.shape.by: str_insamplesheet
    
    genome_overview:
      call.exclude_filter: list__str__(probe_gap|high_probe_dens|min_size|min_probes|min_density)
      show_reference: bool

wildcard_constraints:
  sample_id: str
  sentrix_pos: str
  sentrix_name: str

tools:
  __tool:
    threads: int
    memory: '[0-9]+M?'
    runtime: str
    partition: str