static_data:
    bpm_manifest_file: 'static-data/GSAMD-24v3-0-EA_20034606_A1.bpm'
    egt_cluster_file: 'static-data/GSAMD-24v3-0-EA_20034606_A1.egt'
    csv_manifest_file: ''
    genome_gtf_file: static-data/gencode.hg19.v45.gtf.gz
    penncnv_GCmodel_file: static-data/PennCNV-GCmodel_hg19ExampleArray.gcmodel
    penncnv_pfb_file: static-data/PennCNV-PFB_hg19ExampleArray.pfb
    array_density_file: static-data/density_hg19ExampleArray.bed
    array_gaps_file: static-data/gaps_hg19ExampleArray.bed
#    penncnv_pfb_file: static-data/PennCNV-PFB_hg19_testrun.pfb
#    penncnv_GCmodel_file: static-data/PennCNV-GCmodel_hg19_testrun.gcmodel
#    array_density_file: static-data/density_hg19_testrun.bed
#    array_gaps_file: static-data/gaps_hg19_testrun.bed
    genomeInfo_file: static-data/UCSC_hg19_chromosome-info.tsv

genome_version: 'hg19'
array_name: 'ExampleArray'

raw_data_folder: 'RAW'
data_path: data
log_path: logs

reports:
  StemCNV-check-report:
    file_type: 'html'
    impact.score.critical: 55
