name: scnv-quac
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## General ##
  - python >=3.11
  - snakemake >=7.0,<8.0
  - pathlib
  - apptainer
  - pip
  - pip:
    - loguru
  # # Needed to build local PennCNV
  # - perl = 5.32 #seems to be only version under which PennCNV builds properly
  # - gcc # in case not available, i.e. on some WSL distros
